server:
  port: 7001

# 单机版本
#eureka:
#  instance:
#    hostname: localhost
#
#  client:
#    # false 表示不向注册中心注册自己
#    register-with-eureka: false
#    # false 表示自己端就是注册中心，职责是为辅服务实例，并不需要去检索服务
#    fetch-registry: false
#    service-url:
#      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

# 单机版
eureka:
  instance:
    hostname: localhost  #eureka服务端的实例名字
  client:
    register-with-eureka: false    #表示不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
## 集群版本
#eureka:
#  instance:
#    hostname: eureka7001
#    lease-renewal-interval-in-seconds: 30 # 心跳数据包（默认30s）
#    lease-expiration-duration-in-seconds: 90 # 服务器在收到最后一次心跳数据的等待上限（默认90s），超时之后将提出服务
#
#  client:
#    # false 表示不向注册中心注册自己
#    register-with-eureka: false
#    # false 表示自己端就是注册中心，职责是为辅服务实例，并不需要去检索服务
#    fetch-registry: false
#    service-url:
#      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://localhost:7002/eureka
#  server:
#    enable-self-preservation: false # 自我保护模式关闭
#    eviction-interval-timer-in-ms: 2000 # 回收时间2000ms